services:
  web:
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/Python/VideoHost/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=danila
      - POSTGRES_DB=films

volumes:
  postgres_data: