# Generated by Django 5.1.1 on 2024-10-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_remove_genre_url_remove_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videoapp.genre', verbose_name='жанры'),
        ),
    ]
